/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eRegulation_Buttons */

#ifndef _Included_eRegulation_Buttons
#define _Included_eRegulation_Buttons
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eRegulation_Buttons
 * Method:    Read
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_eRegulation_Buttons_Read
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
