///* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
///* Header for class eRegulation_ADC */
//
//#ifndef _Included_eRegulation_ADC
//#define _Included_eRegulation_ADC
//#ifdef __cplusplus
//extern "C" {
//#endif
///*
// * Class:     eRegulation_ADC
// * Method:    Initialise
// * Signature: (III)V
// */
//JNIEXPORT void JNICALL Java_eRegulation_ADC_Initialise
//  (JNIEnv *, jobject, jint, jint, jint);
//
///*
// * Class:     eRegulation_ADC
// * Method:    Read
// * Signature: ()I
// */
//JNIEXPORT jint JNICALL Java_eRegulation_ADC_Read
//  (JNIEnv *, jobject);
//
///*
// * Class:     eRegulation_ADC
// * Method:    ReadAverage
// * Signature: ()I
// */
//JNIEXPORT jint JNICALL Java_eRegulation_ADC_ReadAverage
//  (JNIEnv *, jobject);
//
//#ifdef __cplusplus
//}
//#endif
//#endif
