/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eRegulation_LCD */

#ifndef _Included_eRegulation_LCD
#define _Included_eRegulation_LCD
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eRegulation_LCD
 * Method:    Clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eRegulation_LCD_Clear
  (JNIEnv *, jobject);

/*
 * Class:     eRegulation_LCD
 * Method:    Write
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_eRegulation_LCD_Write
  (JNIEnv *, jobject, jstring);

/*
 * Class:     eRegulation_LCD
 * Method:    Position
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_eRegulation_LCD_Position
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
