/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eRegulation_Relays */

#ifndef _Included_eRegulation_Relays
#define _Included_eRegulation_Relays
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eRegulation_Relays
 * Method:    OffAll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_eRegulation_Relays_OffAll
  (JNIEnv *, jobject, jint);

/*
 * Class:     eRegulation_Relays
 * Method:    ScanAndSet
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_eRegulation_Relays_ScanAndSet
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
