/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eRegulation_Relay */

#ifndef _Included_eRegulation_Relay
#define _Included_eRegulation_Relay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eRegulation_Relay
 * Method:    On
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_eRegulation_Relay_On
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     eRegulation_Relay
 * Method:    Off
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_eRegulation_Relay_Off
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     eRegulation_Relay
 * Method:    AllOff
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_eRegulation_Relay_AllOff
  (JNIEnv *, jobject, jint);

/*
 * Class:     eRegulation_Relay
 * Method:    IsOn
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_eRegulation_Relay_IsOn
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
